//POST
export const GET_POST = 'POST/GET_POST';
export const DELETE_POST = "POST/DELETE_POST";


//COMMENTS
export const GET_COMMENTS = 'COMMENTS/GET_COMMENTS';
export const DELETE_COMMENT = 'COMMENTS/DELETE_COMMENT';
export const EDIT_COMMENT = 'COMMENTS/EDIT_COMMENT';
export const CREATE_COMMENT = 'COMMENTS/CREATE_COMMENT';